// <auto-generated />
using System;
using APIFLASHMOBI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiFlashMobi.Migrations
{
    [DbContext(typeof(PedidosContext))]
    [Migration("20250522140748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("APIFLASHMOBI.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPostagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoDestinatario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdRemetente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.Property<double>("TamanhoPacote")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
